import type { DeadlineRule } from './types.ts';

/**
 * Katalog default. Angka & dasar hukum di bawah adalah TITIK AWAL — cut-off
 * pelayaran berbeda per carrier/terminal dan regulasi bisa berubah, jadi
 * simpan katalog ini di DB (per customer / per carrier) dan minta tim
 * compliance memverifikasi kolom `basis` sebelum go-live.
 */
export const DEFAULT_RULES: DeadlineRule[] = [
  // ---------------------------------------------------------------- EKSPOR
  {
    code: 'EXP_SI_CLOSING',
    title: 'Closing Shipping Instruction (SI) ke pelayaran',
    category: 'PELAYARAN',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'SI' },
    fallback: { kind: 'DEPARTURE', offsetHours: -48 },
    doneWhen: 'SI_SUBMITTED',
    remindBeforeHours: [48, 24, 6, 2],
    basis: 'Cut-off booking confirmation pelayaran. Fallback ETD-48j hanya estimasi.',
  },
  {
    code: 'EXP_VGM_CLOSING',
    title: 'Closing VGM (Verified Gross Mass)',
    category: 'PELAYARAN',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'VGM' },
    fallback: { kind: 'DEPARTURE', offsetHours: -48 },
    doneWhen: 'VGM_SUBMITTED',
    remindBeforeHours: [24, 6, 2],
    basis: 'SOLAS Chapter VI Reg. 2; batas waktu mengikuti cut-off pelayaran.',
  },
  {
    code: 'EXP_PEB_NPE',
    title: 'PEB (BC 3.0) harus sudah NPE sebelum CY closing',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    roles: ['PPJK'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'CY' },
    fallback: { kind: 'DEPARTURE', offsetHours: -24 },
    doneWhen: 'NPE_ISSUED',
    remindBeforeHours: [48, 24, 6, 2],
    basis: 'Barang ekspor masuk kawasan pabean setelah PEB/NPE (PMK 145/PMK.04/2014 & perubahannya) — verifikasi.',
  },
  {
    code: 'EXP_CY_CLOSING',
    title: 'CY closing — container full harus gate-in terminal',
    category: 'TERMINAL',
    owner: 'OPS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'CY' },
    fallback: { kind: 'DEPARTURE', offsetHours: -24 },
    doneWhen: 'CONTAINER_GATE_IN',
    remindBeforeHours: [24, 6, 2],
    basis: 'Cut-off terminal/pelayaran. Lewat CY closing = risiko shut-out / roll-over.',
  },
  {
    code: 'EXP_DRAFT_BL',
    title: 'Konfirmasi draft B/L ke pelayaran',
    category: 'PELAYARAN',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'DRAFT_BL' },
    doneWhen: 'DRAFT_BL_APPROVED',
    remindBeforeHours: [24, 4],
    basis: 'Cut-off pelayaran. Tanpa fallback: status MISSING_DATA sampai cut-off diinput.',
  },
  {
    code: 'EXP_OUTWARD_MANIFEST',
    title: 'Submit outward manifest BC 1.1 (pos house B/L)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    roles: ['NVOCC', 'CARRIER_AGENT'],
    anchor: { kind: 'DEPARTURE', offsetHours: 24 },
    doneWhen: 'OUTWARD_MANIFEST_SUBMITTED',
    remindBeforeHours: [24, 6, 2],
    basis: 'PMK 158/PMK.04/2017 & perubahannya (manifes keberangkatan) — verifikasi batas jam.',
  },

  // ---------------------------------------------------------------- IMPOR
  {
    code: 'IMP_RKSP',
    title: 'Submit RKSP (Rencana Kedatangan Sarana Pengangkut)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    roles: ['CARRIER_AGENT'],
    anchor: { kind: 'ARRIVAL', offsetHours: -24 },
    doneWhen: 'RKSP_SUBMITTED',
    remindBeforeHours: [48, 24, 6],
    basis: 'PMK 158/PMK.04/2017 & perubahannya — verifikasi batas jam.',
  },
  {
    code: 'IMP_INWARD_MANIFEST',
    title: 'Submit inward manifest BC 1.1 (pos house B/L)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['NVOCC', 'CARRIER_AGENT'],
    anchor: { kind: 'ARRIVAL', offsetHours: 0 },
    doneWhen: 'INWARD_MANIFEST_SUBMITTED',
    remindBeforeHours: [72, 24, 6, 2],
    basis: 'PMK 158/PMK.04/2017 & perubahannya: paling lambat sebelum kedatangan — verifikasi per moda.',
  },
  {
    code: 'IMP_PIB_PRENOTIF',
    title: 'Submit PIB (BC 2.0) sebelum kapal tiba (pre-clearance)',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['PPJK'],
    anchor: { kind: 'ARRIVAL', offsetHours: 0 },
    doneWhen: 'PIB_SUBMITTED',
    remindBeforeHours: [72, 24, 6],
    basis: 'SLA internal (bukan batas regulasi) untuk menekan dwelling time & storage.',
  },
  {
    code: 'IMP_RED_LANE_INSPECTION',
    title: 'Jalur merah — siapkan pemeriksaan fisik',
    category: 'BEA_CUKAI',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['PPJK'],
    anchor: { kind: 'EVENT', event: 'RED_LANE_ASSIGNED', offsetHours: 24 },
    doneWhen: 'PHYSICAL_INSPECTION_DONE',
    remindBeforeHours: [24, 6],
    overdueRepeatHours: 2,
    basis: 'SLA internal; notifikasi langsung saat penetapan jalur merah.',
  },
  {
    code: 'IMP_STORAGE_FREE_TIME',
    title: 'Free time penumpukan (storage) terminal habis',
    category: 'BIAYA',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    anchor: { kind: 'FREE_TIME', from: 'CONTAINER_DISCHARGED', days: 'storageDays' },
    fallback: { kind: 'FREE_TIME', from: 'ARRIVAL', days: 'storageDays' },
    doneWhen: 'CONTAINER_GATE_OUT',
    remindBeforeHours: [48, 24, 6],
    overdueRepeatHours: 24,
    basis: 'Tarif terminal/TPS. Setelah free time tarif penumpukan progresif.',
  },
  {
    code: 'IMP_DEMURRAGE_FREE_TIME',
    title: 'Free time demurrage container habis',
    category: 'BIAYA',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    anchor: { kind: 'FREE_TIME', from: 'CONTAINER_DISCHARGED', days: 'demurrageDays' },
    fallback: { kind: 'FREE_TIME', from: 'ARRIVAL', days: 'demurrageDays' },
    doneWhen: 'CONTAINER_GATE_OUT',
    remindBeforeHours: [72, 24, 6],
    overdueRepeatHours: 24,
    maxOverdueAlarms: 14,
    basis: 'Kontrak/tarif pelayaran.',
  },
  {
    code: 'IMP_DETENTION_FREE_TIME',
    title: 'Free time detention — empty harus kembali ke depo',
    category: 'BIAYA',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    anchor: { kind: 'FREE_TIME', from: 'CONTAINER_GATE_OUT', days: 'detentionDays' },
    doneWhen: 'EMPTY_RETURNED',
    remindBeforeHours: [48, 24, 6],
    overdueRepeatHours: 24,
    maxOverdueAlarms: 14,
    basis: 'Kontrak/tarif pelayaran.',
  },
  {
    code: 'IMP_BTD_LIMIT',
    title: 'Batas Barang Tidak Dikuasai (BTD) — barang belum keluar TPS',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    anchor: { kind: 'EVENT', event: 'CONTAINER_DISCHARGED', offsetHours: 30 * 24 },
    fallback: { kind: 'ARRIVAL', offsetHours: 30 * 24 },
    doneWhen: 'CONTAINER_GATE_OUT',
    remindBeforeHours: [7 * 24, 72, 24],
    basis: 'Barang tidak diselesaikan 30 hari sejak penimbunan di TPS menjadi BTD (UU Kepabeanan ps. 68 & PMK terkait) — verifikasi.',
  },
];
