import type { DeadlineRule } from './types.ts';

/**
 * Katalog default. Batas regulasi mengikuti riset "Riset Aplikasi Freight Forwarding"
 * (docs/REVIEW.md bagian 7); cut-off pelayaran berbeda per carrier/terminal.
 * Kolom `basis` menyebut sumbernya. Tim compliance WAJIB mencocokkan setiap baris dengan
 * teks resmi PMK sebelum go-live; override tanpa deploy lewat tabel `deadline_rule`.
 */

/** Denda manifes (sumber riset: FAQ Bea Cukai & ketentuan sanksi administrasi kepabeanan). */
const MANIFEST_LATE_RISK = 'Denda Rp10 jt s.d. Rp100 jt per keterlambatan, berjenjang bila berulang dalam 6 bulan.';

export const DEFAULT_RULES: DeadlineRule[] = [
  // ---------------------------------------------------------------- EKSPOR
  {
    code: 'EXP_SI_CLOSING',
    title: 'Closing Shipping Instruction (SI) ke pelayaran',
    category: 'PELAYARAN',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'SI' },
    fallback: { kind: 'DEPARTURE', offsetHours: -48 },
    doneWhen: 'SI_SUBMITTED',
    remindBeforeHours: [48, 24, 6, 2],
    basis: 'Cut-off booking confirmation pelayaran. Fallback ETD-48j hanya estimasi.',
  },
  {
    code: 'EXP_VGM_CLOSING',
    title: 'Closing VGM (Verified Gross Mass)',
    category: 'PELAYARAN',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'VGM' },
    fallback: { kind: 'DEPARTURE', offsetHours: -48 },
    doneWhen: 'VGM_SUBMITTED',
    remindBeforeHours: [24, 6, 2],
    basis: 'SOLAS Chapter VI Reg. 2; batas waktu mengikuti cut-off pelayaran.',
  },
  {
    code: 'EXP_PEB_NPE',
    title: 'PEB (BC 3.0) harus sudah NPE sebelum CY closing',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    roles: ['PPJK'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'CY' },
    fallback: { kind: 'DEPARTURE', offsetHours: -24 },
    doneWhen: 'NPE_ISSUED',
    remindBeforeHours: [48, 24, 6, 2],
    basis:
      'PMK 155/PMK.04/2022: PEB paling cepat 7 hari sebelum perkiraan ekspor, paling lambat sebelum barang masuk Kawasan Pabean/terminal. CY closing dipakai sebagai batas gate-in terakhir.',
    risk: 'Container tidak boleh gate-in tanpa NPE: shut-out / roll-over ke kapal berikutnya.',
  },
  {
    code: 'EXP_PEB_BL_UPDATE',
    title: 'Lengkapi data MBL/HBL di PEB setelah kapal berangkat',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['EXPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['PPJK'],
    anchor: { kind: 'DEPARTURE', offsetHours: 3 * 24 },
    doneWhen: 'PEB_BL_UPDATED',
    // Riset: ingatkan pada hari kalender ke-2 setelah keberangkatan.
    remindBeforeHours: [24, 6],
    basis:
      'PMK 155/PMK.04/2022: data Master/House B/L dilengkapi paling lama 3 hari kalender sejak keberangkatan sarana pengangkut. Dihitung 72 jam dari ATD/ETD (konservatif).',
  },
  {
    code: 'EXP_CY_CLOSING',
    title: 'CY closing — container full harus gate-in terminal',
    category: 'TERMINAL',
    owner: 'OPS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'CY' },
    fallback: { kind: 'DEPARTURE', offsetHours: -24 },
    doneWhen: 'CONTAINER_GATE_IN',
    remindBeforeHours: [24, 6, 2],
    basis: 'Cut-off terminal/pelayaran. Lewat CY closing = risiko shut-out / roll-over.',
  },
  {
    code: 'EXP_DRAFT_BL',
    title: 'Konfirmasi draft B/L ke pelayaran',
    category: 'PELAYARAN',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA'],
    anchor: { kind: 'CARRIER_CUTOFF', cutoff: 'DRAFT_BL' },
    doneWhen: 'DRAFT_BL_APPROVED',
    remindBeforeHours: [24, 4],
    basis: 'Cut-off pelayaran. Tanpa fallback: status MISSING_DATA sampai cut-off diinput.',
  },
  {
    code: 'EXP_OUTWARD_MANIFEST',
    title: 'Submit outward manifest BC 1.1 (pos house B/L)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['EXPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['NVOCC', 'CARRIER_AGENT'],
    // Sebelumnya ATD+24 jam; riset: paling lambat SEBELUM keberangkatan.
    anchor: { kind: 'DEPARTURE', offsetHours: 0 },
    doneWhen: 'OUTWARD_MANIFEST_SUBMITTED',
    remindBeforeHours: [24, 12, 6, 2],
    basis: 'PMK 158/PMK.04/2017 jo. PMK 97/PMK.04/2020: outward manifest paling lambat sebelum keberangkatan sarana pengangkut (semua moda).',
    risk: MANIFEST_LATE_RISK,
  },

  // ---------------------------------------------------------------- IMPOR
  {
    code: 'IMP_RKSP',
    title: 'Submit RKSP (Rencana Kedatangan Sarana Pengangkut)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    roles: ['CARRIER_AGENT'],
    anchor: { kind: 'ARRIVAL', offsetHours: -24 },
    doneWhen: 'RKSP_SUBMITTED',
    remindBeforeHours: [48, 24, 6],
    basis: 'PMK 158/PMK.04/2017 & perubahannya — verifikasi batas jam.',
  },
  {
    code: 'IMP_INWARD_MANIFEST',
    title: 'Submit inward manifest BC 1.1 (pos house B/L)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    roles: ['NVOCC', 'CARRIER_AGENT'],
    anchor: { kind: 'ARRIVAL_BY_VOYAGE', thresholdHours: 24, longVoyageOffsetHours: -24, shortVoyageOffsetHours: 0 },
    doneWhen: 'INWARD_MANIFEST_SUBMITTED',
    // H-12 jam: eskalasi khusus dari riset untuk mencegah denda.
    remindBeforeHours: [72, 24, 12, 6, 2],
    basis:
      'PMK 158/PMK.04/2017 jo. PMK 97/PMK.04/2020: laut, waktu tempuh >= 24 jam paling lambat 24 jam sebelum kedatangan; < 24 jam paling lambat sebelum kedatangan. Waktu tempuh = ETD/ATD pelabuhan asal s.d. ETA/ATA.',
    risk: MANIFEST_LATE_RISK,
  },
  {
    code: 'IMP_INWARD_MANIFEST_AIR',
    title: 'Submit inward manifest BC 1.1 udara (pos house AWB)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['IMPORT'],
    modes: ['AIR'],
    roles: ['NVOCC', 'CARRIER_AGENT'],
    anchor: { kind: 'ARRIVAL', offsetHours: 0 },
    doneWhen: 'INWARD_MANIFEST_SUBMITTED',
    remindBeforeHours: [24, 6, 2, 1],
    basis: 'PMK 158/PMK.04/2017 jo. PMK 97/PMK.04/2020: udara, paling lambat sebelum kedatangan sarana pengangkut.',
    risk: MANIFEST_LATE_RISK,
  },
  {
    code: 'IMP_HOUSE_BL_RECONCILE',
    title: 'Rekonsiliasi pos house B/L dengan master B/L (cegah penolakan kode 57)',
    category: 'BEA_CUKAI',
    owner: 'DOCS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    roles: ['NVOCC'],
    anchor: { kind: 'ARRIVAL', offsetHours: 7 * 24 },
    doneWhen: 'HOUSE_BL_RECONCILED',
    // Riset: peringatan kritis pada hari ke-5 setelah kedatangan.
    remindBeforeHours: [48, 24],
    basis:
      'Riset (FAQ Duktek Bea Cukai Tanjung Priok / CEISA 4.0, sumber sekunder): house B/L tanpa rekonsiliasi dengan master B/L dalam 7 hari sejak kedatangan ditolak (kode 57). WAJIB dikonfirmasi ke KPU/KPPBC.',
  },
  {
    code: 'IMP_PIB_PRENOTIF',
    title: 'Submit PIB (BC 2.0) sebelum kapal tiba (pre-clearance)',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['PPJK'],
    anchor: { kind: 'ARRIVAL', offsetHours: 0 },
    doneWhen: 'PIB_SUBMITTED',
    remindBeforeHours: [72, 24, 6],
    basis: 'SLA internal (bukan batas regulasi) untuk menekan dwelling time & storage.',
  },
  {
    code: 'IMP_RED_LANE_INSPECTION',
    title: 'Jalur merah — siapkan pemeriksaan fisik',
    category: 'BEA_CUKAI',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    roles: ['PPJK'],
    anchor: { kind: 'EVENT', event: 'RED_LANE_ASSIGNED', offsetHours: 24 },
    doneWhen: 'PHYSICAL_INSPECTION_DONE',
    remindBeforeHours: [24, 6],
    overdueRepeatHours: 2,
    basis: 'SLA internal; notifikasi langsung saat penetapan jalur merah.',
  },
  {
    code: 'IMP_STORAGE_FREE_TIME',
    title: 'Free time penumpukan (storage) terminal habis',
    category: 'BIAYA',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    anchor: { kind: 'FREE_TIME', from: 'CONTAINER_DISCHARGED', days: 'storageDays' },
    fallback: { kind: 'FREE_TIME', from: 'ARRIVAL', days: 'storageDays' },
    doneWhen: 'CONTAINER_GATE_OUT',
    remindBeforeHours: [48, 24, 6],
    overdueRepeatHours: 24,
    basis: 'Tarif terminal/TPS. Setelah free time tarif penumpukan progresif.',
  },
  {
    code: 'IMP_DEMURRAGE_FREE_TIME',
    title: 'Free time demurrage container habis',
    category: 'BIAYA',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    anchor: { kind: 'FREE_TIME', from: 'CONTAINER_DISCHARGED', days: 'demurrageDays' },
    fallback: { kind: 'FREE_TIME', from: 'ARRIVAL', days: 'demurrageDays' },
    doneWhen: 'CONTAINER_GATE_OUT',
    remindBeforeHours: [72, 24, 6],
    overdueRepeatHours: 24,
    maxOverdueAlarms: 14,
    basis: 'Kontrak/tarif pelayaran.',
  },
  {
    code: 'IMP_DETENTION_FREE_TIME',
    title: 'Free time detention — empty harus kembali ke depo',
    category: 'BIAYA',
    owner: 'OPS',
    directions: ['IMPORT'],
    modes: ['SEA'],
    anchor: { kind: 'FREE_TIME', from: 'CONTAINER_GATE_OUT', days: 'detentionDays' },
    doneWhen: 'EMPTY_RETURNED',
    remindBeforeHours: [48, 24, 6],
    overdueRepeatHours: 24,
    maxOverdueAlarms: 14,
    basis: 'Kontrak/tarif pelayaran.',
  },
  {
    code: 'IMP_BTD_LIMIT',
    title: 'Batas Barang Tidak Dikuasai (BTD) — barang belum keluar TPS',
    category: 'BEA_CUKAI',
    owner: 'CUSTOMS',
    directions: ['IMPORT'],
    modes: ['SEA', 'AIR'],
    anchor: { kind: 'EVENT', event: 'CONTAINER_DISCHARGED', offsetHours: 30 * 24 },
    fallback: { kind: 'ARRIVAL', offsetHours: 30 * 24 },
    doneWhen: 'CONTAINER_GATE_OUT',
    // Riset: eskalasi H-15, H-7, H-3 (+ H-1).
    remindBeforeHours: [15 * 24, 7 * 24, 3 * 24, 24],
    basis:
      'UU Kepabeanan ps. 68 & ketentuan BTD (riset: semangat PMK 145/PMK.04/2014): barang di TPS > 30 hari sejak penimbunan menjadi BTD, dipindah ke TPP, dan dapat dilelang setelah 60 hari di TPP.',
    risk: 'Status BTD: dipindah paksa ke TPP (biaya tambahan), dapat dilelang negara setelah 60 hari.',
  },
];
